export const ALL_POKEMON = 'ALL_POKEMON';

export const MATCHED_POKEMON = 'MATCHED_POKEMON';

export const TOGGLE_SHOW = 'TOGGLE_SHOW';

export const DISPLAY_POKEMON = 'DISPLAY_POKEMON';

export const DISPLAY_POKEMON_ASYNC = 'DISPLAY_POKEMON_ASYNC';

export const SET_SHOW_TO_FALSE = 'SET_SHOW_TO_FALSE';
